import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import "../styles/globals.css";
import "@rainbow-me/rainbowkit/styles.css";

import { Providers } from "./providers";
import { ThemeProvider } from "@/components/theme-provider";
import Header from "./header";
import { Toaster } from "@/components/ui/toaster";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Medical History",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      {/* bg-gradient-to-r from-[#fccb90] to-[#d57eeb] */}
      <body className={cn("min-h-screen bg-background  font-sans antialiased", fontSans.variable)}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          <Providers>
            <Header />
            <main>{children}</main>
          </Providers>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
